apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kafka-dashboards-all
    files:
      - strimzi-kafka-metrics.json
      - strimzi-kafka-bridge-metrics.json
      - strimzi-kafka-oauth-metrics.json

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peer-authentication.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    namespace: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.1.4
    valuesFile: values.yaml
   
