apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - kafka-metrics-configmap.yaml
  - kafka-oauth-metrics-configmap.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peer-authentication.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    namespace: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.1.4
    # includeCRDs: true
    valuesFile: values.yaml
