apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: mtls-disable
  namespace: grafana
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  mtls:
    mode: DISABLE
