apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml
  - topic.yaml
  - metrics-configmap.yaml
  - metrics-service.yaml
  - peer-authentication.yaml
  - cluster-operator-pod-monitor.yaml
  - entity-operator-pod-monitor.yaml
  - kafka-resources-pod-monitor.yaml
  - prometheus-cluster-rule.yaml
  - prometheus-cluster-operator-rule.yaml
  - prometheus-cluster-entity-operator-rule.yaml
