apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: false

namespace: loki

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml

helmCharts:
  - name: loki
    releaseName: loki
    namespace: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.49.0
    valuesFile: values.yaml
