apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: kafka-ui
    releaseName: kafka-ui
    namespace: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    version: 1.5.3
    valuesFile: values.yaml
