apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.29.0
    releaseName: istio-gateway
    namespace: istio-system
    valuesFile: values.yaml
