apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - oauth-sso-secret.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peer-authentication.yaml

helmCharts:
  - name: oauth2-proxy
    releaseName: oauth2-proxy
    namespace: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 10.0.0
    valuesFile: values.yaml
