apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusters/
  # - externalsecrets/

# Apply ordering:
# Helm (Kafka) -> then ExternalSecret (depends on Kafka SA)
# Kustomize itself doesn't enforce order during build,
# but you can apply with kubectl using the right sequence:
# kubectl apply -k . --prune --wait=false
