apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: false

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml
  - sso-external-secret.yaml

helmCharts:
  - name: kafka-ui
    releaseName: kafka-ui
    namespace: kafka-ui
    repo: https://kafbat.github.io/helm-charts
    version: 1.6.0
    valuesFile: values.yaml
