apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peer-authentication.yaml

helmCharts:
  - name: prometheus
    releaseName: prometheus
    namespace: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 27.51.0
    valuesFile: values.yaml
    # includeCRDs: true
