apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mtls-disable
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  mtls:
    mode: DISABLE
