apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice
  namespace: monitoring
spec:
  hosts:
    - "metrics.local.io"
  gateways:
    - gateway
  http:
    - route:
      - destination:
          host: monitoring-kube-prometheus-prometheus
          port:
            number: 9090
