apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peerauthentication.yaml

helmCharts:
  - name: keycloakx
    version: 7.1.3
    releaseName: keycloakx
    namespace: keycloak
    repo: https://codecentric.github.io/helm-charts
    # includeCRDs: true
    valuesFile: values.yaml
