apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: grafana
spec:
  selector:
    app: istio-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - dashboards.local.io
