---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sso-sa
  namespace: grafana
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-sso-secret-store
  namespace: grafana
spec:
  provider:
    vault:
      server: "http://secrets.local.io:32080"
      path: "sso"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "grafana-sso-secret-role"
          serviceAccountRef:
            name: grafana-sso-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: grafana
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: grafana-sso-secret-store
    kind: SecretStore
  target:
    name: grafana-sso-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: grafana
        property: CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: grafana
        property: CLIENT_SECRET
    - secretKey: DB_PASSWORD
      remoteRef:
        key: grafana
        property: DB_PASSWORD
