apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: virtualservice
  namespace: grafana
spec:
  hosts:
    - dashboards.local.io
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana.grafana.svc.cluster.local
            port:
              number: 80
