apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.0.1
    includeCRDs: true
    valuesInline:
      image:
        crds:
          systemAuthDelegator: true
