---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: grafana-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  bootstrap:
    initdb:
      database: grafana_db
      owner: grafana_admin
      secret:
        name: grafana-db-secret
  storage:
    storageClass: standard
    size: 1Gi
