apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster.yaml
  - topic.yaml
  - metrics-configmap.yaml
  - metrics-service.yaml
  - bridge.yaml
  - bridge-metrics-configmap.yaml
  - bridge-virtualservice.yaml
  - bridge-gateway.yaml
  - bridge-sso-external-secret.yaml
  # - connect-sso-external-secret.yaml
  # - connect.yaml
  # - connect-metrics-configmap.yaml
  # - source-connector.yaml
  # - sink-connector.yaml
