apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - peer-authentication.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: strimzi-kafka-operator
    releaseName: strimzi-cluster-operator
    namespace: kafka-operator
    repo: oci://quay.io/strimzi-helm
    version: 0.50.0
    includeCRDs: true
    valuesInline:
      watchAnyNamespace: true
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "9090,9091,9092"
