apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: strimzi-kafka-operator
    releaseName: strimzi-cluster-operator
    namespace: kafka-operator
    repo: oci://quay.io/strimzi-helm
    version: 0.48.0
    includeCRDs: true