apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connect.yaml
  - connect-metrics-configmap.yaml
  - connect-sso-external-secret.yaml
  - connect-prometheus-rule.yaml
  - source-connector.yaml
  - sink-connector.yaml
