---
apiVersion: v1
kind: Service
metadata:
  name: welcome-app-stable-service
  namespace: welcome-app
spec:
  selector:
    app: welcome-app
  ports:
    - port: 80
      targetPort: 8080
