apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - virtualservice.yaml
  - sso-external-secret.yaml

helmCharts:
  - name: kiali-server
    repo: https://kiali.org/helm-charts
    version: 2.20.0
    releaseName: kiali-server
    namespace: kiali-operator
    valuesFile: values.yaml
