auth:
  strategy: openid
  openid:
    authentication_timeout: 600
    insecure_skip_verify_tls: true
    disable_rbac: true
    client_id: kiali
    # secret_name: kiali
    issuer_uri: http://sso.local.io:32080/realms/platform
    scopes:
      - openid
      - profile
      - email
    username_claim: email

deployment:
  secret_name: "kiali"
  cluster_wide_access: true
  # accessible_namespaces:
  #  - '**'

external_services:
  custom_dashboards:
    enabled: true
  
  prometheus:
    url: http://metrics.local.io:32080

  grafana:
    enabled: true
    internal_url: http://grafana.grafana:3000
    external_url: http://dashboards.local.io:32080
    auth:
      type: none

server:
  observability:
    metrics:
      enabled: true
      port: 9090
  web_root: /
