auth:
  strategy: openid
  openid:
    allowed_domains:
      - local.io
    authentication_timeout: 600
    insecure_skip_verify_tls: true
    disable_rbac: true
    client_id: kiali
    issuer_uri: http://sso.local.io:32080/realms/platform
    scopes:
      - openid
      - profile
      - email
      - groups
    username_claim: email

deployment:
  secret_name: "kiali"
  cluster_wide_access: true
  # accessible_namespaces:
  #  - '**'

external_services:
  custom_dashboards:
    enabled: true
  
  prometheus:
    url: http://metrics.local.io:32080

  grafana:
    enabled: true
    # auth:
    #   use_kiali_token: false
    #   type: bearer
    #   token: secret:kiali-grafana-auth:token
    #   insecure_skip_verify: false
    internal_url: http://grafana.grafana.svc.cluster.local
    external_url: http://dashboards.local.io:32080

server:
  observability:
    metrics:
      enabled: true
      port: 9090
  web_root: /
