apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - minio-root-login-external-secret.yaml
  - minio-sso-external-secret.yaml
  - minio-argowf-user-external-secret.yaml
  - gateway.yaml
  - virtualservice.yaml
  - peer-authentication.yaml


helmCharts:
  - name: minio
    releaseName: minio
    namespace: minio
    repo: https://charts.min.io/
    version: 5.4.0
    valuesFile: values.yaml
