apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bridge.yaml
  - bridge-metrics-configmap.yaml
  - bridge-virtualservice.yaml
  - bridge-gateway.yaml
  - bridge-sso-external-secret.yaml
  - bridge-pod-monitor.yaml
  - bridge-prometheus-rule.yaml
