apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: false

namespace: promtail

resources:
  - namespace.yaml

helmCharts:
  - name: promtail
    releaseName: promtail
    namespace: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.17.1
    valuesFile: values.yaml
   