podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"

config:
  clients:
    # - url: http://loki.loki:3100/loki/api/v1/push
    #- url: http://loki-gateway.loki/loki/api/v1/push
    - url: http://logs.local.io:32080/loki/api/v1/push
      timeout: 10s
      backoff_config:
        min_period: 100ms
        max_period: 10s
        max_retries: 10
      # tenant_id: "demo-app"  # if multi-tenancy is enabled
      # Optional basic auth config if enabled:
      #basic_auth:
        #username: root-user
        #password: supersecretpassword

  positions:
    filename: /run/promtail/positions.yaml

  server:
    disable: false
    http_listen_port: 9080
    grpc_listen_port: 0

  # scrape_configs:
  #   - job_name: kubernetes-pods
  #     kubernetes_sd_configs:
  #       - role: pod
  #     relabel_configs:
  #       - source_labels:
  #           - __meta_kubernetes_pod_controller_name
  #         regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
  #         action: replace
  #         target_label: __tmp_controller_name
  #       - source_labels:
  #             - __meta_kubernetes_pod_label_app_kubernetes_io_name
  #             - __meta_kubernetes_pod_label_app
  #             - __tmp_controller_name
  #             - __meta_kubernetes_pod_name
  #         regex: ^;*([^;]+)(;.*)?$
  #         action: replace
  #         target_label: app
  #       - source_labels:
  #           - __meta_kubernetes_pod_node_name
  #         action: replace
  #         target_label: node_name
  #       - source_labels:
  #           - __meta_kubernetes_namespace
  #         action: replace
  #         target_label: namespace
  #       - source_labels:
  #           - __meta_kubernetes_pod_name
  #         action: replace
  #         target_label: pod
  #       - source_labels:
  #           - __meta_kubernetes_pod_container_name
  #         action: replace
  #         target_label: container
  #       - replacement: /var/log/pods/*$1/*.log
  #         separator: /
  #         source_labels:
  #           - __meta_kubernetes_pod_uid
  #           - __meta_kubernetes_pod_container_name
  #         target_label: __path__

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container_name
        - action: replace
          source_labels: [__meta_kubernetes_pod_uid]
          target_label: __path__
          replacement: /var/log/pods/*$1/*.log
          regex: (.*)
