apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - namespace.yaml
  - deploy-cluster.yaml
  - topic.yaml
  # - user.yaml
  - metrics-configmap.yaml
  - metrics-service.yaml
